### ISSUE TITLE
The error 'output size is too small'

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#142]
I'm trying to add ted + fisher dataset training, by merging manifest. The data preparation was successful, but in the training process I've got an error like this:
```
Using bucketing sampler for the following epochs

DataParallel (
  (module): DeepSpeech (
    (conv): Sequential (
      (0): Conv2d(1, 32, kernel_size=(41, 11), stride=(2, 2))
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True)
      (2): Hardtanh (min_val=0, max_val=20, inplace)
      (3): Conv2d(32, 32, kernel_size=(21, 11), stride=(2, 1))
      (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True)
      (5): Hardtanh (min_val=0, max_val=20, inplace)
    )
    (rnns): Sequential (
      (0): BatchRNN (
        (rnn): LSTM(32, 400, bias=False, bidirectional=True)
      )
      (1): BatchRNN (
        (batch_norm): SequenceWise (
        BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
      (2): BatchRNN (
        (batch_norm): SequenceWise (
        BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
      (3): BatchRNN (
        (batch_norm): SequenceWise (
        BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
    )
    (fc): Sequential (
      (0): SequenceWise (
      Sequential (
        (0): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        (1): Linear (400 -> 29)
      ))
    )
    (inference_log_softmax): InferenceBatchLogSoftmax (
    )
  )
)
Number of parameters: 9328368
Traceback (most recent call last):
  File "train.py", line 397, in <module>
    main()
  File "train.py", line 234, in main
    out = model(inputs)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 58, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/d2/jbaik/deepspeech.pytorch/model.py", line 121, in forward
    x = self.conv(x)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 255, in forward
    self.padding, self.dilation, self.groups)
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/functional.py", line 53, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (32, 21, 10). Calculated output size: (7, 1, 0). Output size is too small.
```
I guess this is originated from the data split since I didn't exclude any short length utterances. Is it correct? If so, what's the best choice of min length of utterances?

**Comment by SeanNaren** [comment]
Sorry for the late response. I'd keep the defaults as they are. If you are using the same window size and stride I think the minimum is 0.5s of audio data!

**Comment by ryanleary** [comment]
Think this is something we could address in the data loader to handle this gracefully by ignoring utterances that are too short? cc @SeanNaren

**Comment by SeanNaren** [comment]
Might be a bit difficult to avoid the above error due to us having to calculate the size after the convolutional layers to determine if we have enough time steps. Any ideas on how to do that @ryanleary ?

**Comment by jinserk** [comment]
Um, actually, I've detoured this issue to make zero padding if the input utterance is less than 0.5s. I don't know if there is any minor effects from these padded zeros. In my manifests, 1/3 or utt segments are less than 0.5s from swb and fisher corpus, and I've found that most of normal conversations contains inevitable portion of such super short utterances. I'm still in training, and please share your experience. Thanks!
