### ISSUE TITLE
beam decoder error

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#170]
From the recent update, I found that the beam decoder shows an error as follows:
```
Traceback (most recent call last):
  File "transcribe.py", line 49, in <module>
    lm_beta2=args.lm_beta2, label_size=args.label_size, label_margin=args.label_margin)
  File "/d2/jbaik/deepspeech.pytorch/decoder.py", line 145, in __init__
    self._decoder.set_label_selection_parameters(label_size, label_margin)
AttributeError: 'CTCBeamDecoder' object has no attribute 'set_label_selection_parameters'
```

I've updated [pytorch-ctc](https://github.com/ryanleary/pytorch-ctc.git) but the master branch was updated 4 months ago, and the error wasn't resolved. 

When I blocked the line of calling the missing attribute ```set_label_selection_parameters```, I still got another error like:
```
Traceback (most recent call last):
  File "transcribe.py", line 60, in <module>
    decoded_output = decoder.decode(out.data)
  File "/d2/jbaik/deepspeech.pytorch/decoder.py", line 149, in decode
    out, conf, seq_len, offsets = self._decoder.decode(probs.cpu(), sizes)
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by SeanNaren** [comment]
The main repo for the pytorch-ctc has changed, do this:

```
git clone --recursive https://github.com/parlance/pytorch-ctc.git
cd pytorch-ctc
pip install -r requirements.txt
python setup.py install
```

**Comment by jinserk** [comment]
Oh, I didn't know that. Thanks for the information! :D
