### ISSUE TITLE
transcribe.py throws a dlopen error 

### ISSUE THREAD

**Issue by spakhomov** [SeanNaren/deepspeech.pytorch#190]
Got this error when trying to run transcribe.py with an AN4 model:

Traceback (most recent call last):
  File "transcribe.py", line 1, in <module>
    from data.data_loader import SpectrogramParser
  File "/home/pakh0002/deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/home/pakh0002/deepspeech.pytorch/data/data_loader.py", line 10, in <module>
    import torchaudio
  File "build/bdist.linux-x86_64/egg/torchaudio/__init__.py", line 9, in <module>
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/_th_sox.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/_th_sox.py", line 6, in __bootstrap__
ImportError: dlopen: cannot load any more object with static TLS

Looks like (at least on my machine), dlopen is running out of slots when trying to import the torchaudio module in data/data_loader.py. I was able to work around this issue by moving the import torchaudio statement in data/data_loader.py up a few lines just above line 6 "import librosa." 

transcriber.py ran fine after that - not sure why this was happening - could be specific to my setup but though I'd submit this workaround in case someone else runs into this issue.

**Comment by ryanleary** [comment]
I haven't seen any other reports of similar issues. Would you mind if I close? Seems that it may have something to do with your local configuration (though I'm not sure what might be causing that).

**Comment by spakhomov** [comment]
Yes, please close this issue. It must have to do with something specific to my set up on this one machine. I tried installing deepspeech from scratch on a different machine and it this issue didn't happen with that installation.
