### ISSUE TITLE
minor issue: installation for ctcdecode may need installation of wget

### ISSUE THREAD

**Issue by David-Levinthal** [SeanNaren/deepspeech.pytorch#192]
I am not using anaconda..just native ubuntu 16.04 and python3
I hit this error when invoking the ctcdecode install with pip3
Processing /home/levinth/ctcdecode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-qh2t4e2m-build/setup.py", line 55, in <module>
        os.path.join(this_file, "build.py:ffi")
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/levinth/.local/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/levinth/.local/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/levinth/.local/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-qh2t4e2m-build/build.py", line 7, in <module>
        import wget
    ImportError: No module named 'wget'

a simple sudo pip3 install wget was all that was needed
output of history:
 2000  git clone https://github.com/SeanNaren/deepspeech.pytorch.git
 2001  git clone https://github.com/SeanNaren/warp-ctc.git
 2002  cd warp-ctc/
 2003  mkdir build
 2004  cd build
 2005  cmake ..
 2006  make
 2007  export CUDA_HOME=/usr/local/cuda
 2008  cd ..
 2009  cd pytorch_binding/
 2010  sudo python3 setup.py install
 2011  cd ~/
 2012  sudo apt-get install sox libsox-dev libsox-fmt-all
 2013  git clone https://github.com/pytorch/audio.git
 2014  cd audio
 2015  pip3 install cffi
 2016  sudo python3 setup.py install
 2017  cd ..
 2018  git clone --recursive https://github.com/parlance/ctcdecode.git
 2019  cd ctcdecode/
 2020  pip3 install .
 2021  sudo pip3 install .
 2022  sudo pip3 install wget
 2023  sudo pip3 install .

**Comment by ryanleary** [comment]
Thanks for the report. I'm closing this and created https://github.com/parlance/ctcdecode/issues/50 to track this issue.
