### ISSUE TITLE
Error while importing torchaudio

### ISSUE THREAD

**Issue by saisrinivas047** [SeanNaren/deepspeech.pytorch#228]
Hi 
I am getting this error while importing torchaudio. can someone please help me solve this.
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/torchaudio/__init__.py", line 11, in <module>
    from torchaudio import transforms
  File "build/bdist.linux-x86_64/egg/torchaudio/transforms.py", line 152, in <module>
    class SPECTROGRAM(object):
  File "build/bdist.linux-x86_64/egg/torchaudio/transforms.py", line 166, in SPECTROGRAM
    pad=0, window=torch.hann_window, wkwargs=None):
AttributeError: 'module' object has no attribute 'hann_window'

**Comment by ryanleary** [comment]
Please post this issue on the torchaudio github.

**Comment by saisrinivas047** [comment]
can you specify how to install previous version of torchaudio. I am not finding anything on the internet
