### ISSUE TITLE
what torch and pytorch version? TypeError: forward() takes exactly 3 arguments (2 given) when training

### ISSUE THREAD

**Issue by StephenZengCn** [SeanNaren/deepspeech.pytorch#28]
```
DataParallel (
  (module): DeepSpeech (
    (conv): Sequential (
      (0): Conv2d(1, 32, kernel_size=(41, 11), stride=(2, 2))
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True)
      (2): Hardtanh (min_val=0, max_val=20, inplace)
      (3): Conv2d(32, 32, kernel_size=(21, 11), stride=(2, 1))
      (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True)
      (5): Hardtanh (min_val=0, max_val=20, inplace)
    )
    (rnns): Sequential (
      (0): BatchLSTM (
        (batch_norm): SequenceWise (
        Sequential (
          (0): Linear (672 -> 400)
          (1): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        ))
        (rnn): LSTM(672, 400, bias=False, bidirectional=True)
      )
      (1): BatchLSTM (
        (batch_norm): SequenceWise (
        Sequential (
          (0): Linear (400 -> 400)
          (1): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        ))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
      (2): BatchLSTM (
        (batch_norm): SequenceWise (
        Sequential (
          (0): Linear (400 -> 400)
          (1): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        ))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
      (3): BatchLSTM (
        (batch_norm): SequenceWise (
        Sequential (
          (0): Linear (400 -> 400)
          (1): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        ))
        (rnn): LSTM(400, 400, bias=False, bidirectional=True)
      )
    )
    (fc): Sequential (
      (0): SequenceWise (
      Sequential (
        (0): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True)
        (1): Linear (400 -> 29)
      ))
    )
  )
)
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 145, in main
    out = model(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 40, in forward
    return self.module(input.cuda(self.device_ids[0]))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/demobin/work/github/deepspeech.pytorch/model.py", line 94, in forward
    x = self.rnns(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 63, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/demobin/work/github/deepspeech.pytorch/model.py", line 48, in forward
    x, _ = self.rnn(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes exactly 3 arguments (2 given)
```

**Comment by SeanNaren** [comment]
Hey, I'd suggest building pytorch from source as described [here](https://github.com/pytorch/pytorch#from-source). However the newest conda build should allow us not to pass in hidden states.

**Comment by StephenZengCn** [comment]
thanks for your notice, i have get it runing but i got a out of memory error now :(
```
Epoch: [1][43/48]	Time 0.556 (0.356)	Data 0.001 (0.005)	Loss 70.6029 (70.8962)	
Epoch: [1][44/48]	Time 0.572 (0.361)	Data 0.001 (0.005)	Loss 61.0836 (70.6732)	
Epoch: [1][45/48]	Time 0.638 (0.367)	Data 0.001 (0.005)	Loss 59.0884 (70.4158)	
THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 145, in main
    out = model(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 59, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/demobin/work/github/deepspeech.pytorch/model.py", line 96, in forward
    x = self.rnns(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/demobin/work/github/deepspeech.pytorch/model.py", line 50, in forward
    x, _ = self.rnn(x, (c0, h0))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/rnn.py", line 327, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/rnn.py", line 269, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/rnn.py", line 272, in forward
    fn.workspace = torch.cuda.ByteTensor(workspace_size.value)
RuntimeError: cuda runtime error (2) : out of memory at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu:66
```

**Comment by SeanNaren** [comment]
@StephenZengCn what's your GPU? Try turning down the batch size using the `--batch_size` param

**Comment by StephenZengCn** [comment]
thanks. i training on the other machine, and it worked.
