### ISSUE TITLE
Using pre-trained model

### ISSUE THREAD

**Issue by byuns9334** [SeanNaren/deepspeech.pytorch#285]
Hi, I finished downloading all requirements here and now trying to use the pre-trained model.
When I type  'python test.py --model-path data/librispeech_pretrained.pth --test-manifest data/libri_test_other_manifest.csv --cuda' , I get the following error:

How can I resolve this problem? Thanks for reading! (I've already downloaded libri_test_other_manifest.csv) 

0%|                                                                                           | 0/147 [00:00<?, ?it/s]                                            Traceback (most recent call last):
  File "test.py", line 64, in <module>
    for i, (data) in tqdm(enumerate(test_loader), total=len(test_loader)):
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 941, in __iter__
    for obj in iterable:
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_nex                                            t_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/volume1/byuns9334/deepspeech.pytorch/data/data_loader.py", line 161, in __getitem__
    transcript = self.parse_transcript(transcript_path)
  File "/mnt/volume1/byuns9334/deepspeech.pytorch/data/data_loader.py", line 165, in parse_transcript
    with open(transcript_path, 'r', encoding='utf8') as transcript_file:
TypeError: 'encoding' is an invalid keyword argument for this function

Exception KeyError: KeyError(<weakref at 0x7f074cfe1db8; to 'tqdm' at 0x7f06f4a4d4d0>,) in <bound method tqdm.__del__ of                                               0%|                                                                                           | 0/147 [00:00<?, ?it/s                                            ]> ignored
byuns9334@milab12:~/disk1/deepspeech.pytorch$ python test.py --model-path data/librispeech_pretrained.pth --test-manifest data/libri_test_other_manifest.csv --cuda
  0%|                                                                                                                                       | 0/147 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test.py", line 64, in <module>
    for i, (data) in tqdm(enumerate(test_loader), total=len(test_loader)):
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 941, in __iter__
    for obj in iterable:
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/volume1/byuns9334/deepspeech.pytorch/data/data_loader.py", line 161, in __getitem__
    transcript = self.parse_transcript(transcript_path)
  File "/mnt/volume1/byuns9334/deepspeech.pytorch/data/data_loader.py", line 165, in parse_transcript
    with open(transcript_path, 'r', encoding='utf8') as transcript_file:
TypeError: 'encoding' is an invalid keyword argument for this function

Exception KeyError: KeyError(<weakref at 0x7f9bebd75db8; to 'tqdm' at 0x7f9b937dbdd0>,) in <bound method tqdm.__del__ of   0%|                                                                                                                                       | 0/147 [00:00<?, ?it/s]> ignored

**Comment by ryanleary** [comment]
Use python 3.

**Comment by byuns9334** [comment]
@ryanleary is python 2 not available for this model?

**Comment by byuns9334** [comment]
@ryanleary thanks!
