### ISSUE TITLE
Multiproc is freezing

### ISSUE THREAD

**Issue by adryyandc** [SeanNaren/deepspeech.pytorch#287]
Multiproc is freezing at command:
`python -m multiproc train.py --visdom --cuda --train-manifest data/libri_train_manifest.csv --val-manifest data/libri_val_manifest.csv --hidden-size 800 --hidden-layers 5 --rnn-type gru --batch-size 8 --num-workers $(nproc) --epochs 1`

with 2 x 1080ti gpus and Ubuntu 16.04 + Pytorch 0.3.1 + cuda 9.1 + 390.48 driver (both docker and lxd images)

I checked gpus utilization and is 0% I know that EnforceNotMet is caused by PyTorch but is just an error at termination. Erors at Ctrl + C

```
Number of parameters: 38067968
^CTraceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/root/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/work/deepspeech.pytorch/multiproc.py", line 33, in <module>
    p.wait()
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 1077, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Process Process-7:
Traceback (most recent call last):
Process Process-12:
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-16:
Process Process-2:
Process Process-9:
Process Process-19:
Process Process-3:
Traceback (most recent call last):
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-5:
Process Process-18:
Process Process-20:
Process Process-11:
Process Process-4:
Process Process-15:
Process Process-1:
Process Process-17:
    self._target(*self._args, **self._kwargs)
Process Process-10:
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-14:
    self.run()
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
Process Process-8:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
Process Process-13:
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    self.run()
    racquire()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    self.run()
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    self.run()
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    racquire()
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    racquire()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    r = index_queue.get()
Process Process-6:
Traceback (most recent call last):
Traceback (most recent call last):
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
    r = index_queue.get()
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
    racquire()
    self.run()
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    r = index_queue.get()
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    racquire()
    self.run()
    self._target(*self._args, **self._kwargs)
    racquire()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    self.run()
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    self.run()
    racquire()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    r = index_queue.get()
    self.run()
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    r = index_queue.get()
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    self._target(*self._args, **self._kwargs)
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    racquire()
    r = index_queue.get()
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
    return recv()
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 21, in recv
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
KeyboardInterrupt
    racquire()
    r = index_queue.get()
    racquire()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
KeyboardInterrupt
    r = index_queue.get()
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    r = index_queue.get()
    buf = self.recv_bytes()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
KeyboardInterrupt
    racquire()
KeyboardInterrupt
    racquire()
KeyboardInterrupt
    racquire()
    racquire()
KeyboardInterrupt
    racquire()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
Exception KeyboardInterrupt in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fca2c7dc290>> ignored
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 50, in _worker_loop
    r = index_queue.get()
  File "/root/anaconda2/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    out = model(inputs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 164, in forward
    self._sync_params()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 195, in _sync_params
    dist.broadcast(flat_buffers, 0)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 198, in broadcast
    return torch._C._dist_broadcast(tensor, src, group)
RuntimeError: Interrupted system call
root@ub-ds2:~/work/deepspeech.pytorch# Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/util.py", line 328, in _exit_function
    p.join()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 148, in join
    res = self._popen.wait(timeout)
  File "/root/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/root/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 7709) exited unexpectedly with exit code 1.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/root/anaconda2/lib/python2.7/multiprocessing/util.py", line 328, in _exit_function
    p.join()
  File "/root/anaconda2/lib/python2.7/multiprocessing/process.py", line 148, in join
    res = self._popen.wait(timeout)
  File "/root/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/root/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 7709) exited unexpectedly with exit code 1.
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down

```

**Comment by swethmandava** [comment]
I get the same error, anyone's got a fix?

    torch.distributed.broadcast(tensor, r)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/distributed/__init__.py", line 276, in broadcast
    return torch._C._dist_broadcast(tensor, src, group)
RuntimeError: Interrupted system call

**Comment by buriy** [comment]
Check the second process error (by default, written to GPU_1.log)

**Comment by farisalasmary** [comment]
Sometimes when I run `train.py` it starts executing the first few lines of code and stuck in an infinite loop. I used to kill all python processes when I get into this situation and then rerun the script.
