### ISSUE TITLE
problem with installation of ctc-decode  [Network is unreachable]

### ISSUE THREAD

**Issue by minushuang** [SeanNaren/deepspeech.pytorch#292]
Hi,I have built all of the envs of this project except the ctct-decode.
although I can train the model and test it, the WER & CER are still have much space to improve.
So, I followed the ReadMe and expected to have an improvement with the installation with the CTC Decode.
but when I clone the repository successfully and run the script of  'pip install .' ,the terminal occured the IO Errors as below, and prompt the msg of '[Errno 101] Network is unreachable'.
Does that mean the problem with my network? but I can clone the ctc decode code.
any solution will be appreciated

```
root@hxh:/home/hxh/common_use/ctcdecode# pip install .
Processing /home/hxh/common_use/ctcdecode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-H8hWbY/setup.py", line 55, in <module>
        os.path.join(this_file, "build.py:ffi")
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/hxh/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "/home/hxh/anaconda2/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 193, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-req-build-H8hWbY/build.py", line 22, in <module>
        'third_party/openfst-1.6.7.tar.gz')
      File "/tmp/pip-req-build-H8hWbY/build.py", line 14, in download_extract
        out=dl_path)
      File "/home/hxh/anaconda2/lib/python2.7/site-packages/wget.py", line 526, in download
        (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
      File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 98, in urlretrieve
        return opener.retrieve(url, filename, reporthook, data)
      File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 245, in retrieve
        fp = self.open(url, data)
      File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 213, in open
        return getattr(self, name)(url)
      File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 443, in open_https
        h.endheaders(data)
      File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 1038, in endheaders
        self._send_output(message_body)
      File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 882, in _send_output
        self.send(msg)
      File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 844, in send
        self.connect()
      File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 1255, in connect
        HTTPConnection.connect(self)
      File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 821, in connect
        self.timeout, self.source_address)
      File "/home/hxh/anaconda2/lib/python2.7/socket.py", line 575, in create_connection
        raise err
    IOError: [Errno socket error] [Errno 101] Network is unreachable
   
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-H8hWbY/
 ```

**Comment by ryanleary** [comment]
Not sure. It seems like a network issue with your machine. You need to be able to download OpenFST and Boost. You could also manually download them and put them in the expected location (look at the `build.py` script).
