### ISSUE TITLE
Segmentation fault:Dataloader worker is killed by signal

### ISSUE THREAD

**Issue by Racial** [SeanNaren/deepspeech.pytorch#295]
Hi,
I want to ask some questions about the dataloader worker.  It happens segmentation fault and expect to solve it. Thank you.

**Comment by mansur007** [comment]
Hello,
I have the same issue, 
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 280, in __next__
    idx, batch = self._get_batch()
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
    return self.data_queue.get()
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/mansur/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1730) is killed by signal: Segmentation fault.

**Comment by miguelvr** [comment]
is this with the distributed option?

**Comment by mansur007** [comment]
@miguelvr , hello, I am sorry, I don't understand what you mean(bcs I am a beginner). Can you please elaborate on what you mean? Thank you. 
For more information, I ran it on Ubuntu 14.04 LTS, as follows:

python train.py --train-manifest data/an4_train_manifest.csv --val-manifest data/an4_val_manifest.csv --cuda --batch-size 8 --checkpoint

if I also add --num-workers=0 - then segmentation fault occurs too, but with no additional information.
Thank you

**Comment by ryanleary** [comment]
Are all of your paths in the manifest valid?

**Comment by luckmoon** [comment]
@mansur007 hi, i just solved it by changing gcc 4.8 to gcc 4.9. In additon, I use Centos 7 rather than Ubuntu. Maybe Ubuntu 18.04 update the gcc version to 4.9+. Anyway, thanks for you replying!
