### ISSUE TITLE
train complete but TypeError: checkpoint() takes at least 5 arguments (4 given)

### ISSUE THREAD

**Issue by StephenZengCn** [SeanNaren/deepspeech.pytorch#31]
```
Epoch: [70][48/48]	Time 12.067 (9.480)	Data 0.003 (0.019)	Loss 0.2493 (6.2196)	
Training Summary Epoch: [70]	Average Loss 0.184	
Validation Summary Epoch: [70]	Average WER 25	Average CER 14	
Learning rate annealed to: 0.000000
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    main()
  File "train.py", line 314, in main
    torch.save(checkpoint(model, optimizer, args, len(labels)), args.final_model_path)
TypeError: checkpoint() takes at least 5 arguments (4 given)
```

**Comment by SeanNaren** [comment]
Thanks! This has been fixed in [here](https://github.com/SeanNaren/deepspeech.pytorch/commit/bfab1c36451efaa1e0710f65138cc4367fb3a244).
