### ISSUE TITLE
ImportError: cannot import name 'lib'

### ISSUE THREAD

**Issue by Peiman-m** [SeanNaren/deepspeech.pytorch#313]
When I try to train my network (a.py) in the second epoch I encounter segmentation fault. After modifying __init__.py I get the following error. I've searched a lot but I didn't find anything useful. 
```Peimans-MacBook-Pro:untitled folder peiman$ python3 a.py
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    from warpctc_pytorch import CTCLoss
  File "/anaconda3/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-macosx-10.9-x86_64.egg/warpctc_pytorch/__init__.py", line 8, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ImportError: cannot import name 'lib'
```

**Comment by SeanNaren** [comment]
Going to close this for now, if you run into this issue again feel free to re-open.
