### ISSUE TITLE
Issue w/ TED Dataloader

### ISSUE THREAD

**Issue by ryanleary** [SeanNaren/deepspeech.pytorch#33]
It seems (at least in my setup) that something breaks at the end of the first epoch -- probably due to an issue in the dataloader(?). Haven't dug much into it yet.

```Epoch: [1][4243/4549]	Time 0.592 (0.309)	Data 0.001 (0.004)	Loss 218.8640 (149.7788)
Epoch: [1][4244/4549]	Time 0.584 (0.309)	Data 0.002 (0.004)	Loss 190.2870 (149.7884)
Epoch: [1][4245/4549]	Time 0.576 (0.309)	Data 0.002 (0.004)	Loss 220.6672 (149.8051)
Epoch: [1][4246/4549]	Time 0.582 (0.309)	Data 0.002 (0.004)	Loss 206.2761 (149.8184)
Epoch: [1][4247/4549]	Time 0.598 (0.309)	Data 0.002 (0.004)	Loss 194.7978 (149.8290)
Epoch: [1][4248/4549]	Time 0.603 (0.309)	Data 0.002 (0.004)	Loss 190.6617 (149.8386)
Epoch: [1][4249/4549]	Time 0.583 (0.309)	Data 0.002 (0.004)	Loss 189.1278 (149.8478)
Epoch: [1][4250/4549]	Time 0.601 (0.310)	Data 0.002 (0.004)	Loss 204.6577 (149.8607)
Epoch: [1][4251/4549]	Time 0.585 (0.310)	Data 0.001 (0.004)	Loss 247.6785 (149.8837)
Epoch: [1][4252/4549]	Time 0.616 (0.310)	Data 0.002 (0.004)	Loss 223.9250 (149.9012)
Epoch: [1][4253/4549]	Time 0.592 (0.310)	Data 0.002 (0.004)	Loss 201.2460 (149.9132)
Epoch: [1][4254/4549]	Time 0.590 (0.310)	Data 0.002 (0.004)	Loss 226.0778 (149.9311)
Epoch: [1][4255/4549]	Time 0.592 (0.310)	Data 0.002 (0.004)	Loss 183.1511 (149.9389)
Epoch: [1][4256/4549]	Time 0.601 (0.310)	Data 0.002 (0.004)	Loss 202.0417 (149.9512)
Epoch: [1][4257/4549]	Time 0.585 (0.310)	Data 0.001 (0.004)	Loss 192.3692 (149.9611)
Epoch: [1][4258/4549]	Time 0.617 (0.310)	Data 0.002 (0.004)	Loss 210.9887 (149.9755)
Epoch: [1][4259/4549]	Time 0.616 (0.310)	Data 0.002 (0.004)	Loss 222.2541 (149.9925)
Epoch: [1][4260/4549]	Time 0.605 (0.310)	Data 0.002 (0.004)	Loss 171.1521 (149.9974)
Epoch: [1][4261/4549]	Time 0.606 (0.310)	Data 0.002 (0.004)	Loss 234.3608 (150.0172)
Epoch: [1][4262/4549]	Time 0.608 (0.310)	Data 0.001 (0.004)	Loss 215.2132 (150.0325)
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    main()
  File "train.py", line 169, in main
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/ryan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/home/ryan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 237, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ryan/devel/deepspeech.pytorch/data/data_loader.py", line 125, in _collate_fn
    targets = torch.IntTensor(targets)
RuntimeError: tried to construct a tensor from a int sequence, but found an item of type NoneType at index (2794)```

**Comment by SeanNaren** [comment]
I've pushed a fix [here](https://github.com/SeanNaren/deepspeech.pytorch/commit/4537c2adb18e95e94f3a8a03ef6056863bac0218), could you re-pull master and try?

**Comment by ryanleary** [comment]
Thanks! Rebuilding the corpora and will try. I've got a couple idle Titan X's at the moment, so happy to run this/other benchmarks.

**Comment by ryanleary** [comment]
Came across issue with the fix on Python 3 due to breaking change in how `filter` works. See explanation here: https://github.com/SeanNaren/deepspeech.pytorch/commit/4537c2adb18e95e94f3a8a03ef6056863bac0218#commitcomment-21919205

Otherwise, that seems to have solved it. Made it through the first epoch successfully. Second is currently in progress.

**Comment by ryanleary** [comment]
Through 14 epochs of training now. Think this one is solved by https://github.com/SeanNaren/deepspeech.pytorch/commit/4537c2adb18e95e94f3a8a03ef6056863bac0218.
