### ISSUE TITLE
Missing key(s) in state_dict: "conv.seq_module.0.weight" ... When running inference with pretrained models

### ISSUE THREAD

**Issue by 3210jr** [SeanNaren/deepspeech.pytorch#331]
I am having trouble running inference using a pretrained model that I downloaded.

running: 

` python transcribe.py --model-path models/an4_pretrained.pth --audio-path how_are_you.wav`

returns the error:

```
Traceback (most recent call last):
  File "transcribe.py", line 72, in <module>
    model = DeepSpeech.load_model(args.model_path)
  File "/home/user/deepspeech.pytorch/model.py", line 243, in load_model
    model.load_state_dict(package['state_dict'])
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepSpeech:
	Missing key(s) in state_dict: "conv.seq_module.0.weight", "conv.seq_module.0.bias", "conv.seq_module.1.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_mean", "conv.seq_module.1.running_var", "conv.seq_module.3.weight", "conv.seq_module.3.bias", "conv.seq_module.4.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_mean", "conv.seq_module.4.running_var", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse". 
	Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var". 
	While copying the parameter named "rnns.0.rnn.weight_ih_l0", whose dimensions in the model are torch.Size([2400, 1312]) and whose dimensions in the checkpoint are torch.Size([2400, 672]).
	While copying the parameter named "rnns.0.rnn.weight_ih_l0_reverse", whose dimensions in the model are torch.Size([2400, 1312]) and whose dimensions in the checkpoint are torch.Size([2400, 672]).
```

Thanks you!

**Comment by miguelvr** [comment]
I think the pre-trained models are not compatible anymore. You would have to checkout commit 655cd586de798b3656c9c52242a11cde3d8a6bd4 for it to work

**Comment by 3210jr** [comment]
Hey thanks for the quick response! Your advice works and i also noticed the most recent commit also doesnt work. 

The commit you mentioned works great though. Sticking with this one for now.

**Comment by miguelvr** [comment]
You're welcome. 

If you are going to train your own models, it probably best to use the most recent commit.
