### ISSUE TITLE
Error w/ pretrained model

### ISSUE THREAD

**Issue by bkj** [SeanNaren/deepspeech.pytorch#336]
When I try to run using a pretrained model, I get the following error:

```
root@5899413916a4:/workspace/deepspeech.pytorch# python test.py --model-path librispeech_pretrained.pth --test-manifest data/an4_val_manifest.csv  --cuda
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = DeepSpeech.load_model(args.model_path)
  File "/workspace/deepspeech.pytorch/model.py", line 243, in load_model
    model.load_state_dict(package['state_dict'])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepSpeech:
	Missing key(s) in state_dict: "conv.seq_module.0.weight", "conv.seq_module.0.bias", "conv.seq_module.1.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_mean", "conv.seq_module.1.running_var", "conv.seq_module.3.weight", "conv.seq_module.3.bias", "conv.seq_module.4.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_mean", "conv.seq_module.4.running_var", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse". 
	Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var". 
	size mismatch for rnns.0.rnn.weight_ih_l0: copying a param of torch.Size([2400, 1312]) from checkpoint, where the shape is torch.Size([2400, 672]) in current model.
	size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param of torch.Size([2400, 1312]) from checkpoint, where the shape is torch.Size([2400, 672]) in current model.
```

Any thoughts?  I'm getting the model files from eg:
  https://github.com/SeanNaren/deepspeech.pytorch/releases/download/v1.1/an4_pretrained.pth

Thanks

**Comment by SeanNaren** [comment]
Make sure to use the same commit as the release, it hasn't been updated for the latest master!

**Comment by lyc1993** [comment]
hi, have you fix this issue?
