### ISSUE TITLE
Can't use DataParallel

### ISSUE THREAD

**Issue by hoyden** [SeanNaren/deepspeech.pytorch#339]
I download the last source,but i found that i can't train it on multi-gpu.So i add the code:
> `model = torch.nn.DataParallel(model)`

But then i found error as:

> `/Work/cm/deepspeech.pytorch/model.py:98: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  x, h = self.rnn(x)
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    out, output_sizes = model(inputs, input_sizes)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
    return self.gather(outputs, self.output_device)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    return gather_map(outputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/_functions.py", line 55, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/comm.py", line 186, in gather
    "but expected {}".format(got, expected))
ValueError: gather got an input of invalid size: got 8x61x6317, but expected 8x68x6317`

Could anyone help me?

**Comment by SeanNaren** [comment]
use multiproc! https://github.com/SeanNaren/deepspeech.pytorch#multi-gpu-training
