### ISSUE TITLE
Can't transcribe with --cuda option

### ISSUE THREAD

**Issue by edwardyoon** [SeanNaren/deepspeech.pytorch#367]
I can't transcribe with coda option. It looks like a bug. With below simple code, problem solved. Do you need a PR?

```
+            x = x.cuda()
             x = module(x)
```

```edward@GPU-machine:~/deepspeech2-korean$ python transcribe.py --model-path models/deepspeech_final.pth --audio-path out.wav --offset --cuda
tensor([[[[-0.2412,  0.7020,  0.2198,  ...,  0.9578,  0.4521,  1.6288],
          [-0.0080,  0.3978,  0.3201,  ...,  0.7010,  0.1510,  0.7534],
          [-0.2118, -0.1203, -0.1827,  ...,  0.0186, -0.1379, -0.1394],
          ...,
          [-0.3545, -0.3558, -0.3550,  ..., -0.3546, -0.3539, -0.3541],
          [-0.3550, -0.3554, -0.3550,  ..., -0.3557, -0.3542, -0.3554],
          [-0.3552, -0.3559, -0.3544,  ..., -0.3546, -0.3559, -0.3558]]]])
Traceback (most recent call last):
  File "transcribe.py", line 87, in <module>
    decoded_output, decoded_offsets = transcribe(args.audio_path, parser, model, decoder, device)
  File "transcribe.py", line 60, in transcribe
    out, output_sizes = model(spect, input_sizes)
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/deepspeech2-korean/model.py", line 208, in forward
    x, _ = self.conv(x, output_lengths)
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/deepspeech2-korean/model.py", line 62, in forward
    x = module(x)
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

**Comment by ashupednekar** [comment]
Same issue here.... test is working fine, but transcribe is not.

**Comment by irkjero** [comment]
In transcribe.py in func "transcribe()" change line "spect.to(device)" to "spect =  spect.to(device)"

**Comment by SeanNaren** [comment]
Thanks @irkjero I've added this fix to the master branch!
