### ISSUE TITLE
visdom assert 'AssertionError: Y should be same size as X'

### ISSUE THREAD

**Issue by StephenZengCn** [SeanNaren/deepspeech.pytorch#37]
```
Epoch: [70][48/48]	Time 0.377 (0.251)	Data 0.002 (0.012)	Loss 0.1478 (4.6092)	
Training Summary Epoch: [70]	Average Loss 0.095	
Validation Summary Epoch: [70]	Average WER 25	Average CER 11	
Traceback (most recent call last):
  File "train.py", line 324, in <module>
    main()
  File "train.py", line 306, in main
    update='replace',
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 179, in result
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 603, in line
    append=update == 'append', opts=opts)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 179, in result
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 461, in updateTrace
    assert Y.shape == X.shape, 'Y should be same size as X'
AssertionError: Y should be same size as X
```

**Comment by StephenZengCn** [comment]
the other epochs visdom visualization is fine.

**Comment by StephenZengCn** [comment]
![newplot](https://cloud.githubusercontent.com/assets/16394555/25512955/18e37c64-2c04-11e7-83f7-36ff14901ead.png)

**Comment by SeanNaren** [comment]
Thanks, should be fixed!
