### ISSUE TITLE
AttributeError: 'AverageMeter' object has no attribute 'clone'

### ISSUE THREAD

**Issue by kannadaraj** [SeanNaren/deepspeech.pytorch#377]
Hi Sean @SeanNaren ,

  Great Repo. Thanks for sharing. I followed everything in the tutorial. Single GPU training workign fine. But if i start multi GPU training than i get teh following error. Please help.
```
`Number of parameters: 41187968
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:86: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):

  File "train.py", line 257, in <module>
    data_time = reduce_tensor(data_time, args.world_size, reduce_op_max=True)
  **File "/data1/projects/deepspeech.pytorch/utils.py", line 19, in reduce_tensor
    rt = tensor.clone()
AttributeError: 'AverageMeter' object has no attribute 'clone'
Traceback (most recent call last):**
  
File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/projects/deepspeech.pytorch/multiproc.py", line 49, in <module>
    cmd=p.args)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python', 'train.py', '--cuda', '--train-manifest', 'database/LibriSpeech/train_manifest_sample.csv', '--val-manifest', '/data1/projects/deepspeech.pytorch/database/LibriSpeech/val_manifest_sample.csv', '--world-size', '4', '--rank', '0', '--gpu-rank', '0']' returned non-zero exit status 1.`
```

**Comment by SeanNaren** [comment]
I've removed this erroneous call from the train script, try again using master please!

This was added to sync the data time across all GPUs, for now this isn't necessary but will re-investigate/implement in the future
