### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by zdgithub** [SeanNaren/deepspeech.pytorch#401]
when I ran `sudo nvidia-docker build -t  deepspeech2.docker .` , I got the following errors:
```
Step 1/21 : FROM pytorch/pytorch:1.0-cuda10.0-cudnn7-devel
 ---> fa5b91571a44
Step 2/21 : WORKDIR /workspace/
 ---> Using cache
 ---> 5fe0fcdfaa28
Step 3/21 : RUN apt-get update -y
 ---> Using cache
 ---> 8f3c952e6c4e
Step 4/21 : RUN apt-get install -y git curl ca-certificates bzip2 cmake tree htop bmon iotop sox libsox-dev libsox-fmt-all vim
 ---> Using cache
 ---> 933f55ebd249
Step 5/21 : RUN pip install cython visdom cffi tensorboardX wget
 ---> Using cache
 ---> 3aadf700df07
Step 6/21 : ENV CUDA_HOME=/usr/local/cuda
 ---> Using cache
 ---> 621477ada8d1
Step 7/21 : RUN git clone https://github.com/SeanNaren/warp-ctc.git
 ---> Using cache
 ---> 7391fb2ec51e
Step 8/21 : RUN cd warp-ctc; mkdir build; cd build; cmake ..; make
 ---> Using cache
 ---> e41af9821169
Step 9/21 : RUN cd warp-ctc; cd pytorch_binding; python setup.py install
 ---> Using cache
 ---> f29312da5e5c
Step 10/21 : RUN git clone https://github.com/pytorch/audio.git
 ---> Using cache
 ---> 4c2c7d9e6ad1
Step 11/21 : RUN cd audio; python setup.py install
 ---> Using cache
 ---> 05e34467aa68
Step 12/21 : RUN git clone --recursive https://github.com/parlance/ctcdecode.git
 ---> Using cache
 ---> 8f076799dfcf
Step 13/21 : RUN cd ctcdecode; pip install .
 ---> Running in 83142ad8c780
Processing /workspace/ctcdecode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/opt/conda/lib/python3.6/http/client.py", line 1392, in connect
        super().connect()
      File "/opt/conda/lib/python3.6/http/client.py", line 936, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/opt/conda/lib/python3.6/socket.py", line 724, in create_connection
        raise err
      File "/opt/conda/lib/python3.6/socket.py", line 713, in create_connection
        sock.connect(sa)
    OSError: [Errno 99] Cannot assign requested address
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-eny9hy9p/setup.py", line 43, in <module>
        import build
      File "/tmp/pip-req-build-eny9hy9p/build.py", line 27, in <module>
        'third_party/openfst-1.6.7.tar.gz')
      File "/tmp/pip-req-build-eny9hy9p/build.py", line 16, in download_extract
        wget.download(url, out=dl_path)
      File "/opt/conda/lib/python3.6/site-packages/wget.py", line 526, in download
        (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-eny9hy9p/
The command '/bin/sh -c cd ctcdecode; pip install .' returned a non-zero code: 1
```
And I have added the `CUDA_HOME=/usr/local/cuda` in my `.bashrc`
Can anyone help me to resolve it?

**Comment by jybaek** [comment]
Try `export CUDA_HOME=/usr/local/cuda` instead of your `CUDA_HOME` in `.bashrc`.

**Comment by SunlerZRY** [comment]
I met the same question. I try to change ./bashrc, but it doesn't work. Any method else?

**Comment by SunlerZRY** [comment]
Succeed!
First, I change CUDA arguments in ~/.bashrc as follows:
![image](https://user-images.githubusercontent.com/45224648/62519302-debe6600-b85d-11e9-9a24-91a32adee5c6.png)
Then, I use `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-packageto` replace `pip install .`.
Then run `sudo nvidia-docker build -t deepspeech2.docker`.
