### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by BuaaAlban** [SeanNaren/deepspeech.pytorch#414]
Pytorch  version：1.0.1.post2
cuda version：Cuda compilation tools, release 9.0, V9.0.176
dataset: libraispeech
all environment installed and tested successfully, and I have trained the model on dataset an4 successfully.
I ran the code:
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m multiproc train.py --cuda --device-ids 0,1,2,3 --train-manifest data/libri_train_manifest.csv –val-manifest data/libri_val_manifest.csv --mixed-precision --dynamic-loss-scale --batch-size 20

and I met this problem after the certain step in Epoch 1: and every time it stopped at 2357.
Anyone met the same problem?

poch: [1][2356/2573]	Time 1.463 (1.076)	Data 0.005 (0.005)	Loss 686.9207 (581.8227)	
Epoch: [1][2357/2573]	Time 1.715 (1.077)	Data 0.005 (0.005)	Loss 654.7462 (581.8537)	
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    out, output_sizes = model(inputs, input_sizes)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/apex/parallel/distributed.py", line 473, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhubokang/speech/deepspeech.pytorch-master/model.py", line 215, in forward
    x = rnn(x, output_lengths)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhubokang/speech/deepspeech.pytorch-master/model.py", line 97, in forward
    x, h = self.rnn(x)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhubokang/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhubokang/speech/deepspeech.pytorch-master/multiproc.py", line 46, in <module>
    cmd=p.args)
subprocess.CalledProcessError: Command '['/home/zhubokang/anaconda3/envs/py36/bin/python', 'train.py', '--cuda', '--train-manifest', 'data/libri_train_manifest.csv', '--val-manifest', 'data/libri_val_manifest.csv', '--mixed-precision', '--dynamic-loss-scale', '--batch-size', '20', '--world-size', '4', '--rank', '0', '--gpu-rank', '0']' returned non-zero exit status 1.

**Comment by jybaek** [comment]
The link below will help you.

https://github.com/pytorch/pytorch/issues/17543

**Comment by BuaaAlban** [comment]
> The link below will help you.
> 
> [pytorch/pytorch#17543](https://github.com/pytorch/pytorch/issues/17543)
 do you mean that i need  to update to cuda10? 
However I have run some steps successfully  and my card is GTX1050, not  GTX2050.
thanks

**Comment by jybaek** [comment]
@BuaaAlban If there is any possibility, you should try.

**Comment by BuaaAlban** [comment]
> @BuaaAlban If there is any possibility, you should try.

I have found that Memory keep augmenting, so  I add "torch.cuda.empty_cache()", this time it could go longer, but after 22epoch it stops, the problem is that the memory augment every epoch, some memory need to be released, I don't know where

**Comment by MuruganR96** [comment]
> "torch.cuda.empty_cache()"

@BuaaAlban  can you please tell me, where i have to replace this code

i am also facing same problem. i have 24GB GPU TITAN RTX. i allocated full memory but still same issue persist.

i was just checked stt interfence,
using these three pretrained models,

an4_pretrained_v2.pth
librispeech_pretrained_v2.pth
ted_pretrained_v2.pth

```
CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../librispeech_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
```

CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../an4_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
```
CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../ted_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

how to resolve this issue? can anyone help me? :)

**Comment by BuaaAlban** [comment]
I don't think this is a problem of memory, so    "torch.cuda.empty_cache()" may not help. 
I add this code in the iteration so as to  empty cache in every step.  


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
On 11/18/2019 14:45，Murugan R<notifications@github.com> wrote：

"torch.cuda.empty_cache()"

@BuaaAlban can you please tell me, where i have to replace this code

i am also facing same problem. i have 24GB GPU TITAN RTX. i allocated full memory but still same issue persist.

i was just checked stt interfence,
using these three pretrained models,

an4_pretrained_v2.pth
librispeech_pretrained_v2.pth
ted_pretrained_v2.pth

CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../librispeech_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED


CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../an4_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

CUDA_VISIBLE_DEVICES="3" python transcribe.py --model-path ../ted_pretrained_v2.pth --audio-path /media/user1/storage-1/suneel/stt/checkpoints/testing/6.wav --cuda
cuda device
Traceback (most recent call last):
  File "transcribe.py", line 68, in <module>
    model = load_model(device, args.model_path, args.half)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/utils.py", line 37, in load_model
    model = model.to(device)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/media/user1/storage-1/Murugan/DeepSpeech-2-Pytorch/deepspeech.pytorch/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED


how to resolve this issue? can anyone help me? :)

**Comment by MuruganR96** [comment]
> " may not help.

@BuaaAlban thanks. are you also still not resolved this issue?

@SeanNaren how can i solve this issue? 

i have 24GB GPU memory.

PyTorch 1.0 and CUDA 10.

Thanks.
