### ISSUE TITLE
[transcribe.py] Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by maggieezzat** [SeanNaren/deepspeech.pytorch#423]
The same error as in #362 when trying to run 
`python transcribe.py --model-path librispeech_pretrained.pth --audio-path /content/deepspeech.pytorch/data/an4_dataset/train/an4/wav/an1-mblw-b.wav `

I get the following error : 
```
Traceback (most recent call last):
  File "transcribe.py", line 88, in <module>
    out = model(Variable(spect, volatile=True))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/deepspeech.pytorch-1.2/model.py", line 172, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size
```

In #362 it says that using PyTorch 1.1.0 and Cuda 10.0 that solves the issue, however I am using them and still got the error. @SeanNaren any help ?

**Comment by dendisuhubdy** [comment]
I also got the same issue here

**Comment by jackaduma** [comment]
I also got the same issue here
