### ISSUE TITLE
Problem with torch==1.1.0

### ISSUE THREAD

**Issue by ngochuyenluu** [SeanNaren/deepspeech.pytorch#430]
Hi, I would like to test Deepspeech 2 on my server which is:
- Ubuntu 18.04.2
- Driver version: 390.116
- CUDA 9.0

All the installations are ok but when I launch train.py, they have problem such as:
Traceback (most recent call last):
  File "/home/eylabadmin/.local/lib/python3.6/site-packages/torch/jit/annotations.py", line 95, in parse_type_line
    arg_ann = eval(arg_ann_str, _eval_env)
  File "<string>", line 1, in <module>
NameError: name 'Optional' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from data.data_loader import AudioDataLoader, SpectrogramDataset, BucketingSampler, DistributedBucketingSampler
  File "/home/eylabadmin/deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/home/eylabadmin/deepspeech.pytorch/data/data_loader.py", line 13, in <module>
    import torchaudio
  File "/usr/local/lib/python3.6/dist-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 7, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, legacy, compliance
  File "/usr/local/lib/python3.6/dist-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/usr/local/lib/python3.6/dist-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/functional.py", line 108, in <module>
    @torch.jit.script
  File "/home/eylabadmin/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 824, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
  File "/home/eylabadmin/.local/lib/python3.6/site-packages/torch/jit/annotations.py", line 55, in get_signature
    return parse_type_line(type_line)
  File "/home/eylabadmin/.local/lib/python3.6/site-packages/torch/jit/annotations.py", line 97, in parse_type_line
    raise RuntimeError("Failed to parse the argument list of a type annotation: {}".format(str(e)))
RuntimeError: Failed to parse the argument list of a type annotation: name 'Optional' is not defined.

As I know, this is the change of Pytorch from May 2019 and I tried to install the older version of Pytorch 1.0.0 and Pytorch 1.0.1 but they drived to other errors. After that, I tried to install Pytorch from their commit before they added more function but there are a lot conflicts from gcc and Caffe2. I didn't find the exact version of requirements.txt also. Otherwise, I tried to install by Docker but I didn't success. Is there anyone have the same problem with me? because of the update of Pytorch, I think all the people install Deepspeech.pytorch will meet this error. I tried all the possible ways but I'm out of idea. If there is some ways to get out, thank in advance for it.

**Comment by ngochuyenluu** [comment]
Hi, everyone, I solve the problem, here is some information for someone who has the same situation like me:
Basically, based on the pull request that torchaudio master is not stable and we need to install the latest commit which is on other branch:
https://github.com/SeanNaren/deepspeech.pytorch/pull/425

So I have to do git clone https://github.com/pytorch/audio/tree/v0.2.0 (this branch can be changed depend on the time you try), but this branch is active and more stable than master which has a lot of conflicts with pytorch. After that, I have no problem to train model.
