### ISSUE TITLE
CUDA error after first training epochs using multi-GPU training

### ISSUE THREAD

**Issue by tann9949** [SeanNaren/deepspeech.pytorch#438]
I've been training my model using this setting

`python -m multiproc train.py --train-manifest data/manifest_train.csv --val-manifest data/manifest_val.csv --batch-size 16 --epochs 20 --checkpoint --tensorboard --cuda --mixed-precision --dynamic-loss-scale`

It works fine after the first epoch. However, after the first epoch finish and the code start shuffling the next batch, it comes up with these errors:

```
# Epoch Summary
Learning rate annealed to: 0.000273
Found better validated model, saving to models/deepspeech_final.pth
Shuffling batches...
# Error code below
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: the launch timed out and was terminated (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fd05d6ff441 in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fd05d6fed7a in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7fd05b1f3652 in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7fd05d6efce0 in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7fd05bb8facb in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x1420cb (0x7fd09cc260cb in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3c3104 (0x7fd09cea7104 in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3c3151 (0x7fd09cea7151 in /home/tan_epacsp/.env/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #8: /home/tan_epacsp/.env/bin/python() [0x58170a]
frame #9: /home/tan_epacsp/.env/bin/python() [0x4e9e28]
frame #10: PyEval_EvalFrameEx + 0x4ba8 (0x53b328 in /home/tan_epacsp/.env/bin/python)
frame #11: /home/tan_epacsp/.env/bin/python() [0x53fc97]
frame #12: PyEval_EvalCode + 0x1f (0x5409bf in /home/tan_epacsp/.env/bin/python)
frame #13: /home/tan_epacsp/.env/bin/python() [0x60cb42]
frame #14: PyRun_FileExFlags + 0x9a (0x60efea in /home/tan_epacsp/.env/bin/python)
frame #15: PyRun_SimpleFileExFlags + 0x1bc (0x60f7dc in /home/tan_epacsp/.env/bin/python)
frame #16: Py_Main + 0x456 (0x640256 in /home/tan_epacsp/.env/bin/python)
frame #17: main + 0xe1 (0x4d0001 in /home/tan_epacsp/.env/bin/python)
frame #18: __libc_start_main + 0xf0 (0x7fd0ab000830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #19: _start + 0x29 (0x5d6999 in /home/tan_epacsp/.env/bin/python)

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tan_epacsp/deepspeech.pytorch/multiproc.py", line 46, in <module>
    cmd=p.args)
subprocess.CalledProcessError: Command '['/home/tan_epacsp/.env/bin/python', 'train.py', '--train-manifest', 'data/manifest_train.csv', '--val-manifest', 'data/manifest_val.csv', '--batch-size', '16', '--epochs', '20', '--checkpoint', '--tensorboard', '--cuda', '--mixed-precision', '--dynamic-loss-scale', '--world-size', '2', '--rank', '0', '--gpu-rank', '0']' returned non-zero exit status -6
```

I used my own training set with approximately 275 hours of training data running on gcloud VM using 2 NVIDIA Tesla K80 with 
CUDA 10.1
pytorch 1.1
and Ubuntu 16.04LTS.

I've tried the following:
- upgrade CUDA from 9.0 to 10.1 (didn't work)
- reduce the batch size (didn't work)
- reduce training size to only 5 files (work out just fine but still i'll need to use more than that for training)

Any help is appreciated, Thank you!

**Comment by tann9949** [comment]
closing issues, it seems that my validation set is too large, reducing it solves the problem
