### ISSUE TITLE
Pretrained models don't work

### ISSUE THREAD

**Issue by madhavajay** [SeanNaren/deepspeech.pytorch#443]
I have done the following on an Ubuntu 18.04 CUDA 10 K80 instance.

```
sudo nvidia-docker build -t  deepspeech2.docker .
sudo nvidia-docker run -ti -v `pwd`/data:/workspace/data --entrypoint=/bin/bash --net=host --ipc=host deepspeech2.docker
```
```
root@ubuntu18-gpu-1:/workspace/deepspeech.pytorch# python transcribe.py --model-path ../data/an4_pretrained.pth --audio-path ../data/an4_dataset/test/an4/wav/cen5-menk-b.wav
```

Error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/annotations.py", line 95, in parse_type_line
    arg_ann = eval(arg_ann_str, _eval_env)
  File "<string>", line 1, in <module>
NameError: name 'Optional' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transcribe.py", line 13, in <module>
    from data.data_loader import SpectrogramParser
  File "/workspace/deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/workspace/deepspeech.pytorch/data/data_loader.py", line 13, in <module>
    import torchaudio
  File "/opt/conda/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 7, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, legacy, compliance
  File "/opt/conda/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/opt/conda/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/functional.py", line 256, in <module>
    @torch.jit.script
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 824, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/annotations.py", line 55, in get_signature
    return parse_type_line(type_line)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/annotations.py", line 97, in parse_type_line
    raise RuntimeError("Failed to parse the argument list of a type annotation: {}".format(str(e)))
RuntimeError: Failed to parse the argument list of a type annotation: name 'Optional' is not defined
```

Then I changed torchaudio as suggested by several people, I have tried both:
301e2e9 and d92de5b
Then when I run:
```
root@ubuntu18-gpu-1:/workspace/deepspeech.pytorch# python transcribe.py --model-path ../data/an4_pretrained.pth --audio-path ../data/an4_dataset/test/an4/wav/cen5-menk-b.wav
```

I get this error:
```
root@ubuntu18-gpu-1:/workspace/deepspeech.pytorch# python transcribe.py --model-path ../data/an4_pretrained.pth --audio-path ../data/an4_dataset/test/an4/wav/cen5-menk-b.wav
Traceback (most recent call last):
  File "transcribe.py", line 66, in <module>
    model = load_model(device, args.model_path, args.cuda)
  File "/workspace/deepspeech.pytorch/utils.py", line 46, in load_model
    model = DeepSpeech.load_model(model_path)
  File "/workspace/deepspeech.pytorch/model.py", line 249, in load_model
    model.load_state_dict(package['state_dict'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepSpeech:
	Missing key(s) in state_dict: "conv.seq_module.0.weight", "conv.seq_module.0.bias", "conv.seq_module.1.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_mean", "conv.seq_module.1.running_var", "conv.seq_module.3.weight", "conv.seq_module.3.bias", "conv.seq_module.4.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_mean", "conv.seq_module.4.running_var", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse".
	Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var".
	size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
	size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
```

Is it possible to fix the torch audio problem in the instructions or Dockerfile and release newer pretrained models that match the architecture change if thats the issue? Or something to patch the file?

**Comment by buriy** [comment]
>size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
@SeanNaren this is due to the difference in padding at model.conv .
Also at some point of time "bias=True" <-> "bias=False" option was changed for RNN layers, that's why some unexpected keys here: "Unexpected key(s) in state_dict..." .

**Comment by nhh1501** [comment]
This problem
`rnn_input_size = int(math.floor(rnn_input_size  - 41) / 2 + 1)
        print(rnn_input_size)
        rnn_input_size = int(math.floor(rnn_input_size  - 21) / 2 + 1)`

**Comment by SeanNaren** [comment]
V2 is released with new pre-trained models: https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v.2.0
