### ISSUE TITLE
_torch_sox.cpython-36m-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by youngminpark2559** [SeanNaren/deepspeech.pytorch#444]
Hi. I got this error.
I can find this file in the path  
```
/home/young/anaconda3/envs/py36_torch100_cuda10_b/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/_torch_sox.cpython-36m-x86_64-linux-gnu.so
```

And I successfully compiled all required libraries.

I'm using conda environment (not "base" environment but the environment which I newly created), cuda10, PyTorch 1.0.0, Python 3.6

```
Traceback (most recent call last):
  File "transcribe.py", line 21, in <module>
    from data.data_loader import SpectrogramParser
  File "/mnt/1T-5e7/Code_projects/NLP/Speech_to_text/github.com_SeanNaren_deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/mnt/1T-5e7/Code_projects/NLP/Speech_to_text/github.com_SeanNaren_deepspeech.pytorch/data/data_loader.py", line 13, in <module>
    import torchaudio
  File "/home/young/anaconda3/envs/py36_torch100_cuda10_b/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 5, in <module>
    import _torch_sox
ImportError: /home/young/anaconda3/envs/py36_torch100_cuda10_b/lib/python3.6/site-packages/torchaudio-0.2-py3.6-linux-x86_64.egg/_torch_sox.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
```

**Comment by SeanNaren** [comment]
V2 is released removing the need for torchaudio https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v.2.0
