### ISSUE TITLE
AttributeError: 'DeepSpeech' object has no attribute 'labels'

### ISSUE THREAD

**Issue by sumeet559** [SeanNaren/deepspeech.pytorch#455]
```
Traceback (most recent call last):
  File "transcribe.py", line 71, in <module>
    decoder = BeamCTCDecoder(model.labels, lm_path=args.lm_path, alpha=args.alpha, beta=args.beta,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'DeepSpeech' object has no attribute 'labels'
```

**Comment by SeanNaren** [comment]
This should be fixed with the latest pre-trained models and version, let me know if this is not the case
