### ISSUE TITLE
memory error after one epoch

### ISSUE THREAD

**Issue by RulerOne** [SeanNaren/deepspeech.pytorch#461]
the training stopped after 1 epoch. the information is above and the usage of memory is about 90G（total 128G of the server）.Can you help me solving this problem?

CUDA_VISIBLE_DEVICES=6 python train.py --cuda  --checkpoint --checkpoint-per-batch 100  --opt-level O0 --batch-size 20 --tensorboard --log-dir logs

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 717/717 [07:18<00:00,  1.64it/s]
Validation Summary Epoch: [1]	Average WER 100.000	Average CER 96.888	
Learning rate annealed to: 0.000273
Found better validated model, saving to models/deepspeech_final.pth
Shuffling batches...
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/rulss/anaconda3/envs/DSP2_torch/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by SeanNaren** [comment]
This is strange, what is the number of workers set to? What is the dataset?
