### ISSUE TITLE
got this error when read audio file

### ISSUE THREAD

**Issue by mrmidnight55** [SeanNaren/deepspeech.pytorch#468]
I got this error when I tried to train another audio files. What should I do to solve this correctly

>   File "train.py", line 230, in <module>
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/deepspeech.pytorch/data/data_loader.py", line 161, in __getitem__
    spect = self.parse_audio(audio_path)
  File "/workspace/deepspeech.pytorch/data/data_loader.py", line 108, in parse_audio
    y = load_audio(audio_path)
  File "/workspace/deepspeech.pytorch/data/data_loader.py", line 24, in load_audio
    sample_rate, sound = read(path)
  File "/opt/conda/lib/python3.6/site-packages/scipy/io/wavfile.py", line 246, in read
    raise ValueError("Unexpected end of file.")
ValueError: Unexpected end of file.

**Comment by rajeevbaalwan** [comment]
try torchaudio to read audio instead of scipy.io.wavfile in data_loader.py file

**Comment by mrmidnight55** [comment]
what about soundfile?
I work on this.
