### ISSUE TITLE
Error while computing stft with Librosa at data loading

### ISSUE THREAD

**Issue by shoegazerstella** [SeanNaren/deepspeech.pytorch#470]
After loading a bunch of data, it stops with this error at `Epoch: [1][3/8045]`
The file exists and it is not empty. 

```
Name: librosa
Version: 0.7.1

Name: numpy
Version: 1.17.4
```

```
Epoch: [1][3/8045]	Time 1.413 (1.646)	Data 0.002 (0.331)	Loss 0.0000 (0.0000)	
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/Data/stella/deepspeech.pytorch/data/data_loader.py", line 161, in __getitem__
    spect = self.parse_audio(audio_path)
  File "/mnt/Data/stella/deepspeech.pytorch/data/data_loader.py", line 118, in parse_audio
    win_length=win_length, window=self.window)
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/librosa/core/spectrum.py", line 219, in stft
    y = np.pad(y, int(n_fft // 2), mode=pad_mode)
  File "<__array_function__ internals>", line 6, in pad
  File "/home/stella/.conda/envs/py37/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 814, in pad
    "'constant' or 'empty'".format(axis)
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'
```

**Comment by kksiddharth** [comment]
Hey, any updates on this. I'm getting stuck with a similar error

**Comment by shoegazerstella** [comment]
I am pretty sure the error was that I had 0 sec long audio files in my dataset, but for some reason, when i printed the filename that was being analyzed, it was printing the one before so that's why i missed that. I had to recheck all my audio files duration and discard the broken ones.

**Comment by kksiddharth** [comment]
got you, I had suspected this, thanks for confirming
