### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'

### ISSUE THREAD

**Issue by MuruganR96** [SeanNaren/deepspeech.pytorch#473]
when i was tried inferencing on our repo. i got it this issue, due to torch==1.1.0.

`RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'`

Why i was moved torch==1.0.0 to torch==1.1.0 means,  i was faced dependency issues with my ubuntu 18.04 CUDA - 10.0 . like this

```
$ python warp-ctc/pytorch_bindingsetup.py install

src/binding.cpp:10:11: fatal error: c10/cuda/CUDAGuard.h: No such file or directory
  #include <c10/cuda/CUDAGuard.h>
           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
so changed the PyTorch version 1.1.0. i resolved this dependency issue.
```
pip install numpy
pip install torch==1.1.0 torchvision==0.3.0
pip install wget

git clone https://github.com/SeanNaren/warp-ctc.git
cd warp-ctc; mkdir build; cd build; cmake ..; make

export CUDA_HOME="/usr/local/cuda"
cd ../pytorch_binding && python setup.py install

git clone --recursive https://github.com/NVIDIA/apex.git
cd apex && pip install .

git clone --recursive https://github.com/parlance/ctcdecode.git
cd ctcdecode && pip install .

git clone https://github.com/SeanNaren/deepspeech.pytorch.git
pip install -r requirements.txt
```
after that when i am inferencing, i faced this issue.
```
python transcribe.py --model-path model_files/an4_pretrained_v2.pth --audio-path audio_files/steve-jobs-3.wav --cuda --half

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dell/Murugan_R/11-12-2019/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dell/Murugan_R/11-12-2019/deepspeech.pytorch/model.py", line 191, in forward
    x, _ = self.conv(x, output_lengths)
  File "/home/dell/Murugan_R/11-12-2019/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dell/Murugan_R/11-12-2019/deepspeech.pytorch/model.py", line 67, in forward
    x = x.masked_fill(mask, 0)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'
```
How to resolve this issue?  
Thanks for this great repo as open source.

Regards,
Murugan R

**Comment by MuruganR96** [comment]
i resolved this issue.

> x = x.masked_fill(mask, 0)

here the error was happened.

Fixed it by changing, model.py line 60. **Bool Type tensor typecasting into Byte.**
[Reference](https://github.com/jiesutd/NCRFpp/issues/137#issuecomment-532083287)
 `mask = torch.BoolTensor(x.size()).fill_(0)`
 to  
`mask = torch.BoolTensor(x.size()).fill_(0).byte()`

thank you
