### ISSUE TITLE
CUDA OOM During Multi GPU Training 

### ISSUE THREAD

**Issue by rajeevbaalwan** [SeanNaren/deepspeech.pytorch#478]
@SeanNaren 
I am trying to train deepspeech2 model using 4 2080Ti GPU's with opt_level O0 and loss_scale 1

After completing a certain number of iterations GPU memory explodes suddenly 

This is the stacktrace for training with batch_size 20

  File "train.py", line 301, in <module>
    out_tar, output_sizes_tar, out_features_tar = model(inputs_tar, input_sizes_tar)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 198, in forward
    x = rnn(x, output_lengths)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 97, in forward
    x, h = self.rnn(x)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 210, in forward
    self.num_layers, self.dropout, self. training, self.bidirectional)
RuntimeError: CUDA out of memory. Tried to allocate 72.06 GiB (GPU 1; 10.76 GiB total capacity; 1.69 GiB already allocated; 7.44 GiB free; 693.18 MiB cached)

As You can see it tries to allocate 72 GiB of memory which is huge and it depends on batch-size.
 if i double the batch size to 40 it tries to allocate ~140 GiB of memory.
my training data contains 3-7 sec of audio clips only.
any help on this ??

**Comment by SeanNaren** [comment]
Have you managed to make it run ok through one GPU?

**Comment by rajeevbaalwan** [comment]
No getting the same problem on a single GPU as well.
The only difference is it takes more iterations then multi-GPU

This is the stacktrace for batch-size 10 on single GPU:

Epoch: [1][3199/45218]  Time 0.372 (0.305)      Data 0.002 (0.002)      Loss 2.4919 (16.6532)
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    out_tar, output_sizes_tar, out_features_tar = model(inputs_tar, input_sizes_tar)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 198, in forward
    x = rnn(x, output_lengths)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 97, in forward
    x, h = self.rnn(x)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech3.6/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 210, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: CUDA out of memory. Tried to allocate 69.37 GiB (GPU 0; 10.76 GiB total capacity; 1.70 GiB already allocated; 7.54 GiB free; 600.00 MiB cached)

**Comment by rajeevbaalwan** [comment]
Tried with PyTorch 1.3 CUDA 9.2 result is same

Epoch: [1][1600/22507]  Time 0.448 (0.393)      Data 0.002 (0.004)      Loss 41.2224 (25.3644)  
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    out_tar, output_sizes_tar, out_features_tar = model(inputs_tar, input_sizes_tar)
  File "/home/pankaj/environments/speech-vad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech-vad/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 198, in forward
    x = rnn(x, output_lengths)
  File "/home/pankaj/environments/speech-vad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/pb/iitd/multi-gpu/deepspeech.pytorch/model.py", line 97, in forward
    x, h = self.rnn(x)
  File "/home/pankaj/environments/speech-vad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pankaj/environments/speech-vad/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 210, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: CUDA out of memory. Tried to allocate 141.52 GiB (GPU 0; 10.76 GiB total capacity; 2.04 GiB already allocated; 6.22 GiB free; 1.60 GiB cached)

Before going CUDA OOM GPU memory fluctuates from ~6Gb-~11GB memory after every few iterations.
didn't understand the reason for this  happening after successfully doing few successfull iterations
