### ISSUE TITLE
error when pip install ctcdecoder

### ISSUE THREAD

**Issue by zcy618** [SeanNaren/deepspeech.pytorch#521]
hi when I try to pip install ctcdecoder, I meet one error:

(deepspeech) parallels@parallels-Parallels-Virtual-Platform:~/Desktop/ASR/ctcdecode$ pip install .
Processing /home/parallels/Desktop/ASR/ctcdecode
    ERROR: Command errored out with exit status 1:
     command: /home/parallels/anaconda3/envs/deepspeech/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xlhnsl16/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xlhnsl16/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-xlhnsl16/pip-egg-info
         cwd: /tmp/pip-req-build-xlhnsl16/
    Complete output (48 lines):
    Traceback (most recent call last):
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 1319, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 1252, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 1298, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 1247, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 966, in send
        self.connect()
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 1414, in connect
        super().connect()
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/http/client.py", line 938, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/socket.py", line 728, in create_connection
        raise err
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/socket.py", line 716, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xlhnsl16/setup.py", line 43, in <module>
        import build
      File "/tmp/pip-req-build-xlhnsl16/build.py", line 26, in <module>
        'third_party/openfst-1.6.7.tar.gz')
      File "/tmp/pip-req-build-xlhnsl16/build.py", line 15, in download_extract
        urllib.request.urlretrieve(url, dl_path)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 247, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 543, in _open
        '_open', req)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 1362, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/home/parallels/anaconda3/envs/deepspeech/lib/python3.7/urllib/request.py", line 1321, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(deepspeech) parallels@parallels-Parallels-Virtual-Platform:~/Desktop/ASR/ctcdecode$ 

Could some expert to check this issue please?
Thanks

**Comment by SeanNaren** [comment]
This should be fixed
