### ISSUE TITLE
transcribe.py fails on startup in docker image when attempting to transcribe things

### ISSUE THREAD

**Issue by la3lma** [SeanNaren/deepspeech.pytorch#523]
root@3fcd79c3fa7c:/workspace/deepspeech.pytorch# python transcribe.py --model-path '/s2t_torch/models/foo.pth' --audio-path '/s2t_torch/data/bar.wav' --decoder beam --lm-path '/s2t_torch/data/baz.klm' --alpha 1.3 --beta 0.15 --beam-width 32
Traceback (most recent call last):
  File "transcribe.py", line 24, in <module>
    from data.data_loader import SpectrogramParser
  File "/workspace/deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/workspace/deepspeech.pytorch/data/data_loader.py", line 17, in <module>
    from .spec_augment import spec_augment
  File "/workspace/deepspeech.pytorch/data/spec_augment.py", line 42, in <module>
    matplotlib.use('TkAgg')
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/__init__.py", line 1281, in use
    plt.switch_backend(name)
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 237, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by la3lma** [comment]
The fix is:

-matplotlib.use('TkAgg')
+matplotlib.use('Agg')

in spec_augment.py (from my colleague Petr Taborski). I'll be sending in a PR r.s.n.
