### ISSUE TITLE
How to convert a '.pth' file to a '.pt' file  with 'torch.jit'

### ISSUE THREAD

**Issue by phecda-xu** [SeanNaren/deepspeech.pytorch#535]
hi,

thanks for your excellent work. I have tried to use 'torch.jit' to convert a '.pth' file to a '.pt' file, but it didn't work. 

code is here:

```
import torch
from model import DeepSpeech

model = DeepSpeech.load_model('models/Deepspeech_final.pth')
model.eval()
spect = torch.rand(1, 1, 161, 600).to("cpu")
length = torch.IntTensor([spect.size(3)]).int().to("cpu")
out, out_size = model(spect, length)

traced_script_module = torch.jit.trace(model, (spect, length))
traced_script_module.save("model.pt")
```
error info:

```
 Traceback (most recent call last):
  File "deepspeech.pytorch/AISpeech2/freeze.py", line 12, in <module>
    traced_script_module = torch.jit.trace(model, (spect, length))
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 858, in trace
    check_tolerance, _force_outplace, _module_class)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 991, in trace_module
    module = make_module(mod, _module_class, _compilation_unit, tuple(inputs.keys()))
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 709, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1733, in __init__
    self._modules[name] = make_module(submodule, TracedModule, _compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 709, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1733, in __init__
    self._modules[name] = make_module(submodule, TracedModule, _compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 709, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1462, in init_then_register
    original_init(self, *args, **kwargs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1733, in __init__
    self._modules[name] = make_module(submodule, TracedModule, _compilation_unit)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 705, in make_module
    return torch.jit._recursive.recursive_script(mod, exclude_methods)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 2073, in _get_named_tuple_properties
    annotations.append(torch.jit.annotations.ann_to_type(obj.__annotations__[field]))
  File "deepspeech.pytorch/AISpeech2/venv/lib/python3.5/site-packages/torch/jit/annotations.py", line 258, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[torch.Tensor, NoneType]'
```

Any idea for this or will you add a script for convert ?

Thank you very much!

**Comment by SeanNaren** [comment]
Hey!

I haven't actually looked into this too much but I'm really curious if you get this working. I know due to the time dimension being variable using torch.trace directly will not work, and torch scripting will need to be implemented (See this [issue](https://discuss.pytorch.org/t/when-should-i-use-tracing-rather-than-scripting/53883))

This is something I do want to look into in the near future.

**Comment by phecda-xu** [comment]
> Hey!
> 
> I haven't actually looked into this too much but I'm really curious if you get this working. I know due to the time dimension being variable using torch.trace directly will not work, and torch scripting will need to be implemented (See this [issue](https://discuss.pytorch.org/t/when-should-i-use-tracing-rather-than-scripting/53883))
> 
> This is something I do want to look into in the near future.


I have tried `jit.script` with "lookahead conv"(no "for ..." and no "if ..." in forward function) but failed. It seems like something wrong with BathNorm.

**Comment by kerolos** [comment]
dear @phecda-xu , @SeanNaren  did you find a way to save a model with 'torch.jit'? .
 and how can i streaming this model Deepspeech (online)? 
thanks in advance.
