### ISSUE TITLE
Can this be used with older CUDA version? 

### ISSUE THREAD

**Issue by aditya-hari** [SeanNaren/deepspeech.pytorch#549]
For various reasons, i cannot update my Nvidia drivers and CUDA 9.0 is the latest that I can use on my system. Is it possible to use this with that? I tried installing it using the docker given but that seems to start installing the latest CUDA version

**Comment by SeanNaren** [comment]
You'll need to probably build a new container from source and decrement the version in the Dockerfile if you'd like to use CUDA 9.0/old drivers. The other alternative is to build from source which would also work!

**Comment by aditya-hari** [comment]
Would building from source by following the exact instructions given in the README work then?

**Comment by SeanNaren** [comment]
It should work, let me know if you run into any issues

**Comment by aditya-hari** [comment]
@SeanNaren Okay so I managed to get a CUDA 10.1 system and built from source. Everything seemed to get installed correctly but I am running into an error during the training.   
 
First, I got this before the training started   
`
/opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
`  
 
And towards the end of the first epoch, I got this -  
 
` 
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    hydra_main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 9, in hydra_main
    train(cfg=cfg)
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/training.py", line 252, in train
    target_decoder=evaluation_decoder)
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/testing.py", line 49, in evaluate
    wer = float(total_wer) / num_tokens
ZeroDivisionError: float division by zero
`  
 
I am using the LibriSpeech dataset installed using the script in /data.

**Comment by aditya-hari** [comment]
@SeanNaren So this is now a separate question that I have, but do you have suggestions for how to implement transfer learning with this?

**Comment by aditya-hari** [comment]
Sorry, I meant fine-tuning.

**Comment by SeanNaren** [comment]
Yes! Documentation on how to do so here: https://github.com/SeanNaren/deepspeech.pytorch#checkpoints

**Comment by aditya-hari** [comment]
Thank you, but I am not quite sure I understood this part -   
 
```
If you would like to start from a previous checkpoint model but not continue training, add the training.finetune=true flag to restart training from the checkpointing.continue_from weights  
```  
 
To be clear, does enabling finetuning mean that a new model will be created, with the old one intact?

**Comment by SeanNaren** [comment]
Yes, training will start from the beginning with `training.finetune=true`, but the model will start with the model weights you specify from `continue_from`

**Comment by aditya-hari** [comment]
I get a KeyError when I try to do that.   

` 
Loading state from model /home/user/Desktop/dsp/deepspeech.pytorch/librispeech_pretrained_v2.pth
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    hydra_main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 9, in hydra_main
    train(cfg=cfg)
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/training.py", line 87, in train
    state = TrainingState.load_state(state_path=to_absolute_path(cfg.checkpointing.continue_from))
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/state.py", line 117, in load_state
    amp_state = state['amp']
KeyError: 'amp'
`

**Comment by aditya-hari** [comment]
Hi, so I'm trying to do that but I am getting a KeyError   
 
```
Loading state from model /home/user/Desktop/dsp/deepspeech.pytorch/librispeech_pretrained_v2.pth
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    hydra_main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 9, in hydra_main
    train(cfg=cfg)
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/training.py", line 87, in train
    state = TrainingState.load_state(state_path=to_absolute_path(cfg.checkpointing.continue_from))
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/state.py", line 117, in load_state
    amp_state = state['amp']
KeyError: 'amp'
```  

I am using the librispeech pretrained model from the releases

**Comment by raotnameh** [comment]
Hi @aditya-hari There is one other way, You can edit the dictionary values of the model. Any problem you have can be solved by this.
