### ISSUE TITLE
Unable to use pretrained models for finetuning 

### ISSUE THREAD

**Issue by aditya-hari** [SeanNaren/deepspeech.pytorch#552]
I'm trying to use the librispeech pretained model available in the latest release for training but am running into a KeyError  

```
Loading state from model /home/user/Desktop/dsp/deepspeech.pytorch/librispeech_pretrained_v2.pth
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    hydra_main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/user/anaconda3/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 9, in hydra_main
    train(cfg=cfg)
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/training.py", line 87, in train
    state = TrainingState.load_state(state_path=to_absolute_path(cfg.checkpointing.continue_from))
  File "/home/user/Desktop/dsp/deepspeech.pytorch/deepspeech_pytorch/state.py", line 117, in load_state
    amp_state = state['amp']
KeyError: 'amp'
 ```
 
I changed the config file to specify the manifests, set finetuning to true, and set the continue_from to the pretrained model.

**Comment by SeanNaren** [comment]
This will be fixed within #560
