### ISSUE TITLE
inference fails

### ISSUE THREAD

**Issue by benedekmajor** [SeanNaren/deepspeech.pytorch#558]
Hi,

got an issue while running the docker version.
When trying to start the server for inferencing:

Traceback (most recent call last):
  File "server.py", line 78, in <module>
    main()
  File "server.py", line 61, in main
    model = load_model(device, args.model_path, args.half)
  File "/workspace/deepspeech.pytorch/deepspeech_pytorch/utils.py", line 29, in load_model
    model = DeepSpeech.load_model(model_path)
  File "/workspace/deepspeech.pytorch/deepspeech_pytorch/model.py", line 221, in load_model
    package = torch.load(path, map_location=lambda storage, loc: storage)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute 'CheckpointingConfig' on <module 'deepspeech_pytorch.config' from '/workspace/deepspeech.pytorch/deepspeech_pytorch/config.py'>

**Comment by SeanNaren** [comment]
Thanks, will investigate! Seems like it's a regression from the recent changes.

**Comment by SeanNaren** [comment]
Any chance you could verify this works: https://github.com/SeanNaren/deepspeech.pytorch/pull/559

Sadly it doesn't build a container to look at, so you'd have to check from source by building the container. Maybe you could give the command you're running if that's easier

**Comment by SeanNaren** [comment]
This will be fixed within #560
