### ISSUE TITLE
Docker Build Fails

### ISSUE THREAD

**Issue by avramandrei** [SeanNaren/deepspeech.pytorch#574]
Hello,

I have tried to build the docker file and I get the following error while trying to build CTCDecode: 

```
Traceback (most recent call last):
    File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
      check=True)
    File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-n2d60b9b/setup.py", line 123, in <module>
      cmdclass={'build_ext': BuildExtension}
    File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
      build_ext.build_extensions(self)
    File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
      _build_ext.build_extension(self, ext)
    File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
      with_cuda=with_cuda)
    File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
      raise RuntimeError(message)
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for ctcdecode
```

I have tried to update the system or change the start docker image, but nothing worked. I am out of ideas. Could you help me out?

P.S. I am new to docker.

Thank you,
Andrei

**Comment by SeanNaren** [comment]
Hmm it worked for the build, what command are you using?

I'm running
```
docker build -t deepspeech .
```
