### ISSUE TITLE
error: continue from checkpoint

### ISSUE THREAD

**Issue by hajix** [SeanNaren/deepspeech.pytorch#609]
Hi sean

continue from checkpoint cause an error:

```
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    hydra_main()
  File "/opt/conda/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 253, in run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 185, in run_and_report
    func()
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 256, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 114, in run
    job_subdir_key=None,
  File "/opt/conda/lib/python3.7/site-packages/hydra/core/utils.py", line 107, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 20, in hydra_main
    train(cfg=cfg)
  File "/workspace/deepspeech.pytorch/deepspeech_pytorch/training.py", line 102, in train
    tensorboard_logger.load_previous_values(state.epoch, state.results)
AttributeError: 'TrainingState' object has no attribute 'results'

```

**Comment by SeanNaren** [comment]
Things have changed drastically after the #568 has been merged! If you can re-train models please have a look at master :)

**Comment by hajix** [comment]
Great job.
