### ISSUE TITLE
KeyError: OSS while training

### ISSUE THREAD

**Issue by VectorVP** [SeanNaren/deepspeech.pytorch#622]
Run training with `python train.py +configs=an4 +checkpoint.dirpath=checkpoints` and got such output:

/opt/conda/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
Global seed set to 123456
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:50: UserWarning: plugin <class 'pytorch_lightning.plugins.sharded_plugin.DDPShardedPlugin'> has added additional required plugins as default: [<class 'pytorch_lightning.plugins.sharded_native_amp_plugin.ShardedNativeAMPPlugin'>]Extend this plugin and override `required_plugins`if this conflicts with your additional plugins.
  warnings.warn(*args, **kwargs)
Missing logger folder: /workspace/deepspeech.pytorch/outputs/2021-02-10/08-22-53/lightning_logs
Global seed set to 123456
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
[2021-02-10 08:22:57,441][root][INFO] - Bucket size: 16.00M parameters, model size 82.61M parameters
[2021-02-10 08:22:57,444][root][INFO] - Assuming single node environment. De-activating ShardedDDP buckets
[2021-02-10 08:22:57,444][root][INFO] - ShardedDDP bucket size: 0.00M parameters, model size 82.61M parameters

  | Name              | Type                  | Params
------------------------------------------------------------
0 | conv              | MaskConv              | 251 K 
1 | rnns              | Sequential            | 86.3 M
2 | fc                | Sequential            | 31.7 K
3 | inference_softmax | InferenceBatchSoftmax | 0     
4 | criterion         | CTCLoss               | 0     
5 | wer               | WordErrorRate         | 0     
6 | cer               | CharErrorRate         | 0     
------------------------------------------------------------
86.6 M    Trainable params
0         Non-trainable params
86.6 M    Total params
Epoch 0:   0%|                                                                                                                 | 0/113 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/workspace/deepspeech.pytorch/deepspeech_pytorch/training.py", line 54, in train
    trainer.fit(model, data_loader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 307, in ddp_train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 550, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 718, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 485, in optimizer_step
    model_ref.optimizer_step(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1298, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 286, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 140, in __optimizer_step
    trainer.precision_connector.backend.optimizer_step(trainer, optimizer, closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/native_amp.py", line 75, in optimizer_step
    closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 708, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 816, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 842, in backward
    result.closure_loss = self.trainer.accelerator_backend.backward(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 103, in backward
    closure_loss = self.trainer.precision_connector.backend.backward(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/native_amp.py", line 47, in backward
    model.backward(closure_loss, optimizer, opt_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1162, in backward
    loss.backward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fairscale/nn/data_parallel/sharded_ddp.py", line 312, in reduce
    self._reduced_grads[optimizer] += 1
KeyError: OSS (
Parameter Group 0
    amsgrad: False
    betas: [0.9, 0.999]
    eps: 1e-08
    initial_lr: 0.00015
    lr: 0.00015
    weight_decay: 1e-05
)

How to solve that problem? Thank you in advance.

**Comment by SeanNaren** [comment]
Could you try installing https://github.com/facebookresearch/fairscale/tree/master/fairscale from master and let me know if this works?

If it does I can report to the authors to build a new release

**Comment by VectorVP** [comment]
@SeanNaren Installed it in dev mode and training is running! Thank you!

```

Dev mode:
cd fairscale
pip install -r requirements.txt
pip install -e .

```

**Comment by blefaudeux** [comment]
oh sorry about that, I'm not sure how that passed through unit tests.. I'll make a new release and try to find if I can patch that hole for the next time

**Comment by SeanNaren** [comment]
Awesomsauce Ben got a release out, just do `pip install fairscale` and should work :)
