### ISSUE TITLE
Continue_from checkpoint fails with --cuda

### ISSUE THREAD

**Issue by aaronzira** [SeanNaren/deepspeech.pytorch#63]
This is a reproduction of a traceback I didn't save from last week from a real run. Seems to happen only when the --cuda flag is enabled during the initial run and the continuation. If not using cuda for either, the run continues as expected. Made a quick hacky workaround last week, but it involved hardcoding the last learning rate, and gpu utilization was severely affected.

```
aaron@...$ python train.py --train_manifest data/ted_train_manifest.csv --val_manifest data/ted_val_manifest.csv --checkpoint --checkpoint_per_batch 20 --cuda --continue_from models/deepspeech_checkpoint_epoch_1_iter_20.pth.tar
Directory already exists.
Loading checkpoint model models/deepspeech_checkpoint_epoch_1_iter_20.pth.tar
Traceback (most recent call last):
  File "train.py", line 321, in <module>
    main()
  File "train.py", line 137, in main
    model.load_state_dict(package['state_dict'])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "conv.0.weight" in state_dict'
```

**Comment by SeanNaren** [comment]
Should be fixed thanks to @ryanleary
