### ISSUE TITLE
ModuleNotFoundError: No module named 'hydra_configs.pytorch_lightning'

### ISSUE THREAD

**Issue by jqiu2** [SeanNaren/deepspeech.pytorch#635]
Hello, 

I know this question may be a little stupid, but I keep getting this error when trying to run inference on my machine. I installed hydra core and upgraded pip(I am using mac OS) but didn't help. I installed PyTorch lightening separately still had no luck. Here is the error information: 

Traceback (most recent call last):
  File "transcribe.py", line 5, in <module>
    from deepspeech_pytorch.inference import transcribe
  File "/Users/qiujinyi/Desktop/Audio_processing/SQA/deepspeech.pytorch-master/deepspeech_pytorch/inference.py", line 10, in <module>
    from deepspeech_pytorch.loader.data_loader import SpectrogramParser
  File "/Users/qiujinyi/Desktop/Audio_processing/SQA/deepspeech.pytorch-master/deepspeech_pytorch/loader/data_loader.py", line 14, in <module>
    from deepspeech_pytorch.configs.train_config import SpectConfig, AugmentationConfig
  File "/Users/qiujinyi/Desktop/Audio_processing/SQA/deepspeech.pytorch-master/deepspeech_pytorch/configs/train_config.py", line 4, in <module>
    from hydra_configs.pytorch_lightning.callbacks import ModelCheckpointConf
ModuleNotFoundError: No module named 'hydra_configs.pytorch_lightning'

I must be missing something in my environment that I don't know. Any help will be appreciated!

**Comment by lytzV** [comment]
Did you run pip install -r requirements.txt?
This is the library you needed: git+https://github.com/romesco/hydra-lightning/#subdirectory=hydra-configs-pytorch-lightning
