### ISSUE TITLE
AttributeError: 'DeepSpeech' object has no attribute 'audio_conf'

### ISSUE THREAD

**Issue by VinACE** [SeanNaren/deepspeech.pytorch#636]
]$ python server.py
/bin/sh: sox: command not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

[2021-04-16 08:12:21,289][root][INFO] - Setting up server...
Traceback (most recent call last):
  File "server.py", line 74, in main
    audio_conf=model.audio_conf,
  File "/opt/anaconda3/envs/dspeech/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'DeepSpeech' object has no attribute 'audio_conf'

**Comment by VinACE** [comment]
I am i missing some code part.
