### ISSUE TITLE
Facing type error while giving the command for training

### ISSUE THREAD

**Issue by Shehan-Irteza-Pranto** [SeanNaren/deepspeech.pytorch#647]
TGlobal seed set to 123456
Traceback (most recent call last):
  File "train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/home/aims/deepspeech2_v2/deepspeech.pytorch/deepspeech_pytorch/training.py", line 25, in train
    checkpoint_callback = FileCheckpointHandler(
  File "/home/aims/deepspeech2_v2/deepspeech.pytorch/deepspeech_pytorch/checkpoint.py", line 16, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'prefix'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Training.py file: https://github.com/SeanNaren/deepspeech.pytorch/blob/master/deepspeech_pytorch/training.py

**Comment by uygarrr** [comment]
Same.

**Comment by kanuarj** [comment]
Use ```export  HYDRA_FULL_ERROR=1``` command before running the train.py to handle ```Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace```.

**Comment by uygarrr** [comment]
```
Global seed set to 123456
Error executing job with overrides: ['+configs=an4']
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    hydra_main()
  File "/home/usr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main  sr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main                      env/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main
ne 368, in _runsr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra              env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
ne 214, in run_sr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report          env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
ne 211, in run_sr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report          env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
ne 371, in <lamsr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 371, in <lambda>                env/lib/python3.7/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
ne 110, in run sr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 110, in run                     env/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 110, in run
3, in return_vasr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/core/utils.py", line 233, in return_value                 env/lib/python3.7/site-packages/hydra/core/utils.py", line 233, in return_value
0, in run_job  sr/anaconda3/envs/env/lib/python3.7/site-packages/hydra/core/utils.py", line 160, in run_job                      env/lib/python3.7/site-packages/hydra/core/utils.py", line 160, in run_jobi
    train(cfg=cfg)
  File "/home/deepspeech.pytorch/deepspeech_pytorch/training.py", line 26, in train sr/deepspeech.pytorch/deepspeech_pytorch/training.py", line 26, in train                       deepspeech.pytorch/deepspeech_pytorch/training.py", line 26, in train
l              sr/deepspeech.pytorch/deepspeech_pytorch/checkpoint.py", linn                                  /deepspeech.pytorch/deepspeech_pytorch/checkpoint.py", line 26, inn s                                                                                                    nn  wswasawsile "/home/deepspeech.pytorch/deepspeech_pytorch/checkpoint.py", linn
e 26, in __init__
    prefix=cfg.prefix

```

Ended up with this trace. I tried to downgrade hydra since it looks like a hydra related problem. Nevertheless I got a similar error with the addition of

```
UserWarning: register_resolver() is deprecated.
See https://github.com/omry/omegaconf/issues/426 for migration instructions.

  OmegaConf.register_resolver(name, f)
```

**Comment by kanuarj** [comment]
@uygarrr Even I'm stuck with the same error now. This issue hasn't been raised nor solved earlier. But this is where everyone will get stuck. I tried finding some solutions for it but haven't able to reach anywhere. I hope the contributors take a look at this.

**Comment by harryfyodor** [comment]
I encounter the same problem and get stuck for many hours... It seems that it's a problem of hydra or pytorch_lightning.

**Comment by kanuarj** [comment]
@uygarrr @harryfyodor please follow issue #649. I've resolved the error.

**Comment by uygarrr** [comment]
@kanuarj it solved mine too!
