### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by kanuarj** [SeanNaren/deepspeech.pytorch#649]
Even after tackling the Hydra errors by using `export HYDRA_FULL_ERROR=1`, the next hurdle stands here.
```
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    hydra_main()
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/home/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/home/deepspeech.pytorch-master/deepspeech_pytorch/training.py", line 26, in train
    cfg=cfg.checkpoint
  File "/home/deepspeech.pytorch-master/deepspeech_pytorch/checkpoint.py", line 26, in __init__
    prefix=cfg.prefix
TypeError: __init__() got an unexpected keyword argument 'prefix'
```
Assistance Required.

**Comment by maneesh06** [comment]
I also got the same error. have you solved it??

**Comment by kanuarj** [comment]
@maneesh06 Not yet. The last thing I was able to discover was some issue with pytorch lightening hydra configs. I hope someone provides assistance.

**Comment by Levi0223** [comment]
I got the same issue.

**Comment by elch10** [comment]
I fixed this with `pip install pytorch-lightning==1.2.9`

**Comment by kanuarj** [comment]
@elch10 Ran into some other error.
```
train.py:19: UserWarning: 
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main(config_name="config")
Global seed set to 123456
Error executing job with overrides: ['data.train_path=dataset/train_manifest.json', 'data.val_path=dataset/val_manifest.json']
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    hydra_main()
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
    overrides=args.overrides,
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/User/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/home/User/Downloads/deepspeech.pytorch-master/deepspeech_pytorch/training.py", line 37, in train
    is_distributed=cfg.trainer.gpus > 1
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by elch10** [comment]
@kanuarj try also when running use command line parameter `trainer.gpus`

I have 1 gpu and I use so `python train.py data.train_path=... data.val_path=... trainer.gpus=1`. By `...` I mean some paths.

**Comment by kanuarj** [comment]
@elch10 Your advice is helpful. Although got different error after resolving some minute errors.
```
RuntimeError: CUDA out of memory. Tried to allocate 1.10 GiB (GPU 0; 5.94 GiB total capacity; 4.48 GiB already allocated; 189.81 MiB free; 4.67 GiB reserved in total by PyTorch)
```
Although I tried reducing the batch size it keeps generating this particular error. Reduced to 8 from 64 but does not work. Any fix or particular Hyperparameter fix ?

**Comment by elch10** [comment]
@kanuarj if you type `python train.py -h`, you'll see list of parameters.

There is model parameters:
```
model:
  rnn_type: lstm
  hidden_size: 1024
  hidden_layers: 5
```

Try to reduce them. E.g. using cmd parameters `model.hidden_size=128` and `model.hidden_layers=1` among with reduced batch size.

But I see you have 5 GB on GPU. You can increase/decrease this hyperparameters until errors disappear.

**Comment by kanuarj** [comment]
@elch10 It worked. You're a gem. Will check for some epochs and see how it goes. Does it automatically save the checkpoints or we need to specify. You know which file it is ?

**Comment by reuben** [comment]
In general it'd be nice to have a requirement specification with fully pinned versions for all deps, to avoid problems like this. Does anyone have a working virtual environment for this project? If so, I'd appreciate if you could share the output of `pip freeze` (run in the venv) so that I can install known working versions of the deps.

**Comment by kanuarj** [comment]
@reuben CUDA 11.2 and CuDNN 9.1
```
fairscale==0.3.7
Flask==1.1.2
google-cloud-storage==1.38.0
hydra-core==1.1.0rc1
jupyter==1.0.0
librosa==0.7.0
matplotlib==3.0.3
numpy==1.20.3
optuna==2.7.0
pytest==4.3.1
python-Levenshtein==0.12.2
pytorch-lightning==1.2.9
scipy==1.2.1
sklearn==0.0
sox==1.4.1
torch==1.8.1
torchaudio==0.8.1
torchelastic==0.2.0
tqdm==4.60.0
wget==3.2

```

**Comment by reuben** [comment]
@kanuarj thanks!

**Comment by li-xx-5** [comment]
may i ask how can i select the beam search decoder, thank you.
