### ISSUE TITLE
Error when running train.py

### ISSUE THREAD

**Issue by lintangsutawika** [SeanNaren/deepspeech.pytorch#66]
I checked out the previous issues regarding similiar matter, but the solutions don't seem to help. 

```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from data.data_loader import AudioDataLoader, SpectrogramDataset
  File "/home/lintangsutawika/deeplearning/deepspeech.pytorch/data/__init__.py", line 1, in <module>
    from . import data_loader
  File "/home/lintangsutawika/deeplearning/deepspeech.pytorch/data/data_loader.py", line 8, in <module>
    import torchaudio
  File "build/bdist.linux-x86_64/egg/torchaudio/__init__.py", line 5, in <module>
    
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/__init__.py", line 3, in <module>
    
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/_th_sox.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/torchaudio/_ext/th_sox/_th_sox.py", line 6, in __bootstrap__
ImportError: /home/lintangsutawika/anaconda2/lib/python2.7/site-packages/torch/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/lib/x86_64-linux-gnu/libsox.so.2)

```

**Comment by ryanleary** [comment]
This is an issue related to your torchaudio installation (likely related to the compiler & libraries packaged with your version of anaconda).

**Comment by SeanNaren** [comment]
As Ryan said this is definitely an issue as to how this was compiled. I would suggest having a look at [this](https://github.com/SeanNaren/deepspeech.pytorch/issues/13#issuecomment-303386763) and following the steps to install pytorch!
