### ISSUE TITLE
Key 'period' not in 'ModelCheckpointConf'

### ISSUE THREAD

**Issue by cuijianaaa** [SeanNaren/deepspeech.pytorch#670]
I run 
```
python train.py +configs=an4
```
but got error，but I can't find any "period" in the code, don't know why, any help?  I use the latest master code
```
Key 'period' not in 'ModelCheckpointConf'
    full_key: checkpoint.period
    object_type=ModelCheckpointConf
```
Details:
```
 python train.py +configs=an4
/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    from_shell=from_shell,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 250, in _load_configuration_impl
    defaults=defaults_list.defaults, repo=caching_repo
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 519, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 452, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 450, in merge_with
    self._merge_with(*others)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 474, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 357, in _map_merge
    dest_node._merge_with(src_value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 474, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 392, in _map_merge
    dest[key] = src._get_node(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 311, in __setitem__
    key=key, value=value, type_override=ConfigKeyError, cause=e
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 517, in _set_item_impl
    target_node_ref = self._get_node(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 167, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'period' not in 'ModelCheckpointConf'
    full_key: checkpoint.period
    object_type=ModelCheckpointConf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 24, in <module>
    hydra_main()
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/main.py", line 52, in decorated_main
    config_name=config_name,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/utils.py", line 378, in _run_hydra
    lambda: hydra.run(
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/utils.py", line 381, in <lambda>
    overrides=args.overrides,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 92, in run
    run_mode=RunMode.RUN,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 563, in compose_config
    from_shell=from_shell,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 148, in load_configuration
    raise ConfigCompositionException().with_traceback(sys.exc_info()[2]) from e
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    from_shell=from_shell,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 250, in _load_configuration_impl
    defaults=defaults_list.defaults, repo=caching_repo
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 519, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 452, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 450, in merge_with
    self._merge_with(*others)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 474, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 357, in _map_merge
    dest_node._merge_with(src_value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 474, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 392, in _map_merge
    dest[key] = src._get_node(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 311, in __setitem__
    key=key, value=value, type_override=ConfigKeyError, cause=e
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 517, in _set_item_impl
    target_node_ref = self._get_node(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 167, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/cj/venvs/deepspeech/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
hydra.errors.ConfigCompositionException

```

**Comment by cuijianaaa** [comment]
I find the root cause, the latest [hydra-lightning](https://github.com/romesco/hydra-lightning/blob/d208362f55534b7bc6c3f696dc1ea4e863006261/hydra-configs-pytorch-lightning/hydra_configs/pytorch_lightning/callbacks.py#L37-L38) https://github.com/romesco/hydra-lightning/blob/d208362f55534b7bc6c3f696dc1ea4e863006261/hydra-configs-pytorch-lightning/hydra_configs/pytorch_lightning/callbacks.py#L37-L38 conflict with [class ModelCheckpointConf](https://github.com/SeanNaren/deepspeech.pytorch/blob/b91e3397262724f280f273e9c58fce388e40e47b/deepspeech_pytorch/configs/lightning_config.py#L7)
